seed: 0

common:
  input_size        : 224
  arch              : resnet50
  sound_dir         : ../dataset/elise/sounds
  mfcc_dir          : ../dataset/elise/mfcc
  model_dir         : ./models
  annotation_dir    : ./annotation
  datalist_path     : ./annotation/youtube.csv
  allpair_path      : ./annotation/all_pair.csv

learning:
  k_fold            : 3
  split_id          : 0
  batch_size        : 16
  n_worker          : 2
  n_sample          : 10
  epochs            : 100
  optimizer:
    algorithm       : 'Adam'
    initial_lr      : 0.1
  margin            : 1.0
  save_ths          : 3
  log:
    save            : True
    dir             : ./learning_logs
  use_amp           : True

inference:
  batch_size        : 16
  n_worker          : 2
  window_wid        : 2
  log:
    save            : False
    dir             : ./inference_logs
  enable_multiproc  : False