common:
  version   : v0.1
  input_size: 224
  arch      : resnet
  path:
    annotation_dir: ./smygw/annotation
    mfcc_dir      : ../dataset/mfcc
    model_dir     : ../model

learning:
  split_id  : 0
  batch_size: 2
  n_worker  : 2
  n_sample  : 10
  epochs    : 100
  lr        : 0.0001
  margin    : 1.0
  seed      : 0
  save_ths  : 3
  path:
    log_dir : ./smygw/learning/logs/

inference:
  batch_size: 16
  n_worker  : 2
  seed      : 0
  window_wid: 2
  path:
    log_dir   : ./smygw/inference/logs/
