version:
  data: v0.1
  code: v0.1
  param: v0.1

common:
  input_size    : 224
  arch          : resnet50
  sound_dir     : ../dataset/sounds
  mfcc_dir      : ../dataset/mfcc
  model_dir     : ./smygw/models
  annotation_dir: ./smygw/annotation
  datalist_path : ./smygw/annotation/youtube.csv
  allpair_path  : ./smygw/annotation/all_pair.csv

learning:
  split_id  : 0
  batch_size: 2
  n_worker  : 2
  n_sample  : 10
  epochs    : 3
  lr        : 0.0001
  margin    : 1.0
  seed      : 0
  save_ths  : 3
  log_dir   : ./smygw/learning/logs

inference:
  batch_size: 16
  n_worker  : 2
  seed      : 0
  window_wid: 2
  log_dir   : ./smygw/inference/logs
