seed: 0

version:
  data: v0.1
  code: v0.1
  param: v0.1

common:
  input_size    : 224
  arch          : resnet50
  sound_dir     : ../dataset/sounds
  mfcc_dir      : ../dataset/mfcc
  model_dir     : ./models
  annotation_dir: ./annotation
  datalist_path : ./annotation/youtube.csv
  allpair_path  : ./annotation/all_pair.csv

learning:
  k_fold    : 3
  split_id  : 0
  batch_size: 2
  n_worker  : 2
  n_sample  : 10
  epochs    : 3
  lr        : 0.0001
  margin    : 1.0
  save_ths  : 3
  log_dir   : ./learning/logs

inference:
  batch_size: 16
  n_worker  : 2
  window_wid: 2
  log_dir   : ./inference/logs
  enable_multiprocessing: False