seed                : 0
debug               : False

model:
  base              : resnet152
  pretrained        : True
  architecture      : PDR           # [PDR, APR]
  disable_bad       : False
  disable_attention : False

data:
  target            : psa
  feature           : 'mel_spectrogram' # [mel_spectrogram, mfcc]
  img_size          : 224
  time_len          : 0.5

learning:
  train:
    batch_size      : 8
  test:
    batch_size      : 8
  sampling:
    method          : sparse        # [dense, sparse]
    n_frame         : 3
  loss:
    method          : marginal_loss # [marginal_loss, softplus]
    margin          : 1.0
    dif_weight      : 0.5
  optimizer:
    algorithm       : 'Adam'
    initial_lr      : 0.1
    sgd_momentum    : 0.9
    decrease_epoch  : 30
    gamma           : 0.5
    accumulate_epoch: 16            # equals to batch_size
    clip_gradient   : 1.0
  augmentation:
    add_noise       : False
    time_masking    : False
  k_fold            : 3
  cross_validation  : False
  epochs            : 100
  n_worker          : 4
  use_amp           : False
  eval_dataset      : False

inference:
  n_frame           : 128
  n_worker          : 4
  save_log          : True