seed                : 0

model:
  base              : resnet18
  pretrained        : True
  architecture      : PDR        # [PDR, APR, APR_TCN, TCN_APR]
  disable_bad       : False
  disable_attention : False
  tcn:
    levels          : 4
    n_unit          : 250
    kernel_size     : 4
    dropout         : 0.05


data:
  target            : elise
  img_size          : 224
  mfcc_window       : 0.5

learning:
  k_fold            : 3
  split_id          : 0
  batch_size        : 8
  n_worker          : 2
  sampling:
    method          : sparse # [dense, sparse]
    n_frame         : 3
  epochs            : 300
  loss:
    method          : marginal_loss # [marginal_loss, softplus]
    margin          : 1.0
    enable_sim_loss : False
  optimizer:
    algorithm       : 'Adam'
    initial_lr      : 0.1
  clip_gradient     : 1.0
  save_ths          : 3
  use_amp           : True
  evaluate_dataset  : False
  resume:
    enable          : False
    log_dir         : './learning_logs/psa/PDR/12-31-21-19-26'

inference:
  batch_size        : 16
  n_worker          : 2
  save_log          : False
  enable_multiproc  : False
  model_dir         : './learning_logs/psa/PDR/12-31-21-19-26'