seed                : 0

model:
  base              : resnet18
  pretrained        : True
  architecture      : TCN_APR        # [PDR, APR, APR_TCN, TCN_APR]
  disable_bad       : True
  disable_attention : False
  tcn:
    levels          : 2
    n_unit          : 256
    kernel_size     : 4
    dropout         : 0.05

data:
  target            : psa
  img_size          : 224
  mfcc_window       : 0.5

learning:
  k_fold            : 3
  cross_validation  : False
  batch_size        : 2
  n_worker          : 2
  sampling:
    method          : dense # [dense, sparse]
    n_frame         : 16
  epochs            : 100
  loss:
    method          : marginal_loss # [marginal_loss, softplus]
    margin          : 1.0
    enable_sim_loss : False
  optimizer:
    algorithm       : 'Adam'
    initial_lr      : 0.1
    decrease_epoch  : 20
    gamma           : 0.5
  accumulate_epoch  : 16            # equlats to batch_size
  clip_gradient     : 1.0
  save_ths          : 3
  use_amp           : False
  eval_dataset      : False
  augmentation:
    add_noise       : True
    time_masking    : True
  resume:
    enable          : False
    log_dir         : './learning_logs/psa/PDR/12-31-21-19-26'

inference:
  batch_size        : 16
  n_worker          : 2
  save_log          : False
  enable_multiproc  : False
  model_dir         : './learning_logs/psa/PDR/12-31-21-19-26'