version   : v0.1
split_id  : 0
input_size: 224
batch_size: 2
n_worker  : 2
n_sample  : 10
epochs    : 100
lr        : 0.0001
margin    : 1.0
seed      : 0
save_ths  : 3
path:
  annotation_dir: ./smygw/annotation
  mfcc_dir      : ../mfcc
  log_dir       : ./smygw/learning/logs/
  model_dir     : ../model

